server:
  port: 18088
  shutdown: graceful
  netty:
    connection-timeout: 5s

spring:
  application:
    name: ai-novel-server
  data:
    mongodb:
      uri: mongodb://mongo:123456@localhost:27017/ainoval?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: true
      password: 123456
      username: mongo
      database: ainovel
      authentication-database: admin
  webflux:
    base-path: /
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    root: INFO
    com.ainovel: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO
    reactor.netty: INFO
    com.ainovel.server: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# 自定义配置
ainovel:
  security:
    jwt:
      secret-key: ${JWT_SECRET:changeme_in_production_environment}
      expiration-time: 86400000  # 24小时，单位毫秒
      refresh-token-expiration: 604800000  # 7天，单位毫秒
  performance:
    virtual-threads:
      enabled: true
    monitoring:
      enabled: true
  version-control:
    enabled: true
    auto-save-history: true
    max-history-count: 20

# 向量存储配置
vectorstore:
  chroma:
    url: http://localhost:18000
    collection: ainovel
    use-random-collection: false
    reuse-collection: true

# 代理配置
proxy:
  enabled: true
  host: localhost
  port: 6888


jwt:
  secret: aiNovelSecretKey12345678901234567890
  expiration: 86400000
  refresh-expiration: 604800000

ai:
  model:
    default: gpt-3.5-turbo
    temperature: 0.7
    max-tokens: 2048

jasypt:
  encryptor:
    password: YOUR_SECRET_ENCRYPTION_KEY_HERE
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator