server:
  port: 18088
  shutdown: graceful
  netty:
    connection-timeout: 5s

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: ai-novel-server
  data:
    mongodb:
      uri: mongodb://mongo:123456@localhost:27017/ainoval?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: true
      password: 123456
      username: mongo
      database: ainovel
      authentication-database: admin
  webflux:
    base-path: /
  lifecycle:
    timeout-per-shutdown-phase: 30s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 4
        max-concurrency: 8
        retry:
          enabled: false
    connection-timeout: 5000
    template:
      mandatory: true
      receive-timeout: 30000
      reply-timeout: 30000

logging:
  level:
    root: INFO
    com.ainovel: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO
    reactor.netty: INFO
    com.ainovel.server: DEBUG
    com.ainovel.server.task: INFO
    org.springframework.amqp: INFO
  request: true
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%X{traceId:-}] [%X{userId:-}] [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[tasks.execution.time]": true
      percentiles:
        "[tasks.execution.time]": [0.5, 0.95, 0.99]
      slo:
        "[tasks.execution.time]": [1000ms, 5000ms, 10000ms]

# 自定义配置
ainovel:
  security:
    jwt:
      secret-key: ${JWT_SECRET:changeme_in_production_environment}
      expiration-time: 86400000  # 24小时，单位毫秒
      refresh-token-expiration: 604800000  # 7天，单位毫秒
  performance:
    virtual-threads:
      enabled: true
    monitoring:
      enabled: true
  version-control:
    enabled: true
    auto-save-history: true
    max-history-count: 20
  storage:
    default-provider: alioss
    covers-path: covers
    # 是否在启动时测试OSS连接
    test-on-startup: true
    # 阿里云OSS配置
    aliyun:
      endpoint: https://oss-cn-shanghai.aliyuncs.com
      access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID}
      access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
      bucket-name: ${ALIYUN_OSS_BUCKET_NAME}
      base-url: ${ALIYUN_OSS_BASE_URL}
      region: cn-shanghai
  ai:
    default-prompts:
      scene-to-summary: "请根据以下小说场景内容，生成一段简洁的摘要。\n场景内容:\n{input}\n参考信息:\n{context}"
      summary-to-scene: "请根据以下摘要/大纲，结合参考信息，生成一段详细的小说场景。\n摘要/大纲:\n{input}\n参考信息:\n{context}"
    rag:
      # RAG检索相关配置
      retrieval-k: 5
    # Resilience配置
    resilience:
      timeout:
        duration: 30s
      retry:
        max-attempts: 3
        backoff:
          initial-delay: 1s
          multiplier: 2

# 向量存储配置
vectorstore:
  chroma:
    url: http://localhost:18000
    collection: ainovel
    use-random-collection: false
    reuse-collection: true

# 代理配置
proxy:
  enabled: true
  host: localhost
  port: 6888


jwt:
  secret: aiNovelSecretKey12345678901234567890
  expiration: 86400000
  refresh-expiration: 604800000

ai:
  model:
    default: gpt-3.5-turbo
    temperature: 0.7
    max-tokens: 2048

jasypt:
  encryptor:
    password: AINoval_Secure_Encryption_Key_2025
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

# 限流器配置
task:
  # 限流配置
  ratelimiter:
    # 限流器类型: memory (基于内存) 或 redis (分布式)
    type: memory
    # 默认限流配置
    default:
      # 每秒许可数量 (QPS)
      rate: 10.0
      # 突发容量 (令牌桶最大容量)
      burstCapacity: 20
      # 获取许可的默认超时时间(毫秒)
      defaultTimeoutMillis: 5000
    # 各AI提供商或模型的特定限流配置
    providers:
      openai:
        rate: 5.0
        burstCapacity: 10
        defaultTimeoutMillis: 3000
      anthropic:
        rate: 3.0
        burstCapacity: 6
        defaultTimeoutMillis: 3000
      gpt-4:
        rate: 2.0
        burstCapacity: 4
        defaultTimeoutMillis: 10000
  # 重试配置
  retry:
    maxAttempts: 5
    initialDelayMillis: 5000
    maxDelayMillis: 3600000 # 1 hour
    backoffFactor: 2.0
    jitterFactor: 0.1
    # 添加缺失的 delays 配置，使用默认值
    delays: 15000,60000,300000
  # 关闭配置
  shutdown:
    awaitTerminationTimeout: PT30S # ISO-8601 duration
