name: ainoval
description: AI驱动的小说创作平台
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_client_sse: ^2.0.3
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7 # 使用最新版本

  # 状态管理
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5

  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0

  # UI组件
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0

  # 工具
  intl: ^0.19.0
  uuid: ^3.0.7
  http: ^1.1.0
  url_launcher: ^6.1.12
  file_picker: ^5.3.3
  share_plus: ^7.1.0
  flutter_markdown: ^0.6.17
  dio: ^5.4.0
  logging: ^1.2.0
  # 国际化
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^6.1.3
  chrono: ^0.1.0
  fluttertoast: ^8.2.5 # Use the latest version
  flutter_portal: ^1.1.4 # 或者最新兼容版本

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  # 正确声明资源目录
  assets:
  - assets/images/
  - assets/icons/
  - assets/fonts/
  # 正确声明字体
  fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto-Regular.ttf
    - asset: assets/fonts/Roboto-Bold.ttf
      weight: 700
    - asset: assets/fonts/Roboto-Italic.ttf
      style: italic
  - family: NotoSansSC
    fonts:
    - asset: assets/fonts/NotoSansSC-Regular.ttf
    - asset: assets/fonts/NotoSansSC-Bold.ttf
      weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
